# Default configuration for arm-softmmu

CONFIG_NAND=y
CONFIG_ECC=y
CONFIG_SERIAL=y
CONFIG_SD=y
CONFIG_SSI_SD=y
CONFIG_SMC91C111=y
CONFIG_PFLASH_CFI01=y
CONFIG_PFLASH_CFI02=y
CONFIG_SSI=y
CONFIG_SSI_M25P80=y
